# Generated by Django 5.2.4 on 2025-07-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kopi',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='gambar_kopi/'),
        ),
    ]
